### ISSUE TITLE
Array of hashes is always evaluated as missing

### ISSUE THREAD

**Issue by tstrachota** [Apipie/apipie-bindings#25]
Parameters having type "array of hashes" with some required field in the inner hash are always evaluated as missing. API calls with such parameters always fail on validation.

For example API action documented as:
```ruby
param :host, Hash, :required => true, :action_aware => true do
  param :interfaces_attributes, Array, :desc => N_("Host's network interfaces.") do
    param :mac, String, :desc => N_("MAC address of interface."), :required => true
  end
end
```
always fails, even with parameters:
```ruby
{
  'host' => {
    'interfaces_attributes' => [
      { 'mac' => '001122334455' }
    ]
  }
}
```

**Comment by mbacovsky** [comment]
Fixed with https://github.com/Apipie/apipie-bindings/pull/26
