### ISSUE TITLE
support rest-client 1.8

### ISSUE THREAD

**Issue by mmoll** [Apipie/apipie-bindings#27]
Debian/testing already brings rest-client 1.8.0, so it's highly likely that the next Ubuntu LTS release will bring it, too. In my light tests with hammer, everything worked fine, the only noticable thing is that verify_ssl is on by default.

As Ruby 1.8.7 still has to be supported, this has somehow to be taken care of.

**Comment by mbacovsky** [comment]
Similar request comes also form Fedora world. There is issue with bindings test suite as rest_client 1.8 changed some classes API. I'm investigating the necessary changes.

**Comment by mbacovsky** [comment]
Fixed with PR #28
