### ISSUE TITLE
index action returns inconsistent data type

### ISSUE THREAD

**Issue by miroswan** [Apipie/apipie-bindings#33]
When called on :smart_proxies, it returns an array of results. When called on :config_templates, it returns a hash, with the first key being the name of the resource, then all found resources. It would make sense that the api returns consistent data types. 

```
[{"smart_proxy"=>
   {"name"=>"foreman-test.dal.com",
     "id"=>1,
     "url"=>"https://foreman-test.dal.com:8443",
     "created_at"=>"2016-02-14T09:23:12Z",
     "updated_at"=>"2016-02-14T09:23:12Z"}}]
```
vs
```
{"config_templates" => [{"config_template"=>{"name"=>"test", "template"=>"  # This is a Chef managed template\n", "snippet"=>true, "audit_comment"=>nil, "id"=>60}}]}
```

**Comment by miroswan** [comment]
Api v2 fixes this.

**Comment by mbacovsky** [comment]
@miroswan, aha, I was curious, where the data come from. V1 explains that. Thanks for the explanantion.
Anyway, apipie-bindings is generic wrapper and just pass data without touching them, so this should be filed rather against Foreman API.
