### ISSUE TITLE
Can't search for resources with spaces in the names

### ISSUE THREAD

**Issue by miroswan** [Apipie/apipie-bindings#35]
This is probably more of an issue with the Foreman api, but I couldn't find a place to submit an issue. You cannot use search filters on resources by name parameter if there is a space in the name. Many of the default resources have spaces in the name, so this is problematic.

**Comment by domcleal** [comment]
Quote it?  e.g. `name = "foo"`

**Comment by miroswan** [comment]
Ah, that did the trick! I went straight to escaping with %20. Thanks.
